### PR TITLE
Make tunnels fail over

### LINKED ISSUE #606: Add IDs to client tunnel workers, more tunnel features.
When a client makes multiple connections to a tunnel, the connections are indistinguishable in logs. Add IDs and print them. 

Other features to look into:

- Make sure a client tunnel can be reloaded instantly through an api hit.
- If a tunnel stays down for more than N minutes, re-check client info for a new tunnel.

### PR DESCRIPTION
**Pull request by davidnewhall**
- Requires https://github.com/golift/mulery/pull/43
- ^ Found a bug: https://github.com/golift/mulery/pull/44
- Make tunnels fail over.
- Add UI to pick tunnels.
- Closes #606 

Requires two new endpoints on the website. One to update the active tunnel, and another to update the tunnels list in the startup payload. Both work on nightly now.

### CODE REVIEW

**Comment by davidnewhall** [comment]
Found a bug in the json/encoding package in the go stdlib. Apparently a recent change to map encoding has introduced a problem. 
```
[ERROR] 2024/04/16 00:42:10 http: panic serving [::1]:60577: runtime error: index out of range [9] with length 9
goroutine 107 [running]:
net/http.(*conn).serve.func1()
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:1898 +0xb0
panic({0x103a2a700?, 0x14000d2e120?})
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/panic.go:770 +0x124
encoding/json.(*encodeState).marshal.func1()
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/encoding/json/encode.go:293 +0x80
panic({0x103a2a700?, 0x14000d2e120?})
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/panic.go:770 +0x124
encoding/json.mapEncoder.encode({0x140000491d8?}, 0x140004ea340, {0x103985420?, 0x1400108d920?, 0x14000049208?}, {0x44?, 0xba?})
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/encoding/json/encode.go:746 +0x58c
encoding/json.(*encodeState).reflectValue(0x140004ea340, {0x103985420?, 0x1400108d920?, 0x102d5469c?}, {0x98?, 0x92?})
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/encoding/json/encode.go:321 +0x70
encoding/json.(*encodeState).marshal(0x14000583bc0?, {0x103985420?, 0x1400108d920?}, {0xe4?, 0xc?})
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/encoding/json/encode.go:297 +0xc0
encoding/json.(*Encoder).Encode(0x14000049408, {0x103985420, 0x1400108d920})
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/encoding/json/stream.go:209 +0xa4
github.com/Notifiarr/notifiarr/pkg/client.(*Client).pingTunnels(0x14000166370, {0x103ac38a0, 0x140010882a0}, 0x102faf498?)
	/Volumes/Storage/david/go/src/github.com/Notifiarr/notifiarr/pkg/client/tunnel.go:264 +0x338
net/http.HandlerFunc.ServeHTTP(0x140010d26c0?, {0x103ac38a0?, 0x140010882a0?}, 0x10411b3d8?)
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:2166 +0x38
github.com/Notifiarr/notifiarr/pkg/client.(*Client).checkAuthorized-fm.(*Client).checkAuthorized.func1({0x103ac38a0, 0x140010882a0}, 0x140010d26c0)
	/Volumes/Storage/david/go/src/github.com/Notifiarr/notifiarr/pkg/client/handlers_gui.go:63 +0x150
net/http.HandlerFunc.ServeHTTP(0x1400108d200?, {0x103ac38a0?, 0x140010882a0?}, 0x14001098468?)
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:2166 +0x38
github.com/Notifiarr/notifiarr/pkg/client.(*Client).addUsernameHeader-fm.(*Client).addUsernameHeader.func1({0x103ac38a0, 0x140010882a0}, 0x140010d26c0)
	/Volumes/Storage/david/go/src/github.com/Notifiarr/notifiarr/pkg/client/handlers.go:194 +0x88
net/http.HandlerFunc.ServeHTTP(0x1400007a000?, {0x103ac38a0?, 0x140010882a0?}, 0x1?)
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:2166 +0x38
github.com/Notifiarr/notifiarr/pkg/client.(*Client).countRequest-fm.(*Client).countRequest.func1({0x103ac3900, 0x14000462ae0}, 0x140010d26c0)
	/Volumes/Storage/david/go/src/github.com/Notifiarr/notifiarr/pkg/client/handlers.go:212 +0x1f8
net/http.HandlerFunc.ServeHTTP(0x1400108d200?, {0x103ac3900?, 0x14000462ae0?}, 0x14000d28011?)
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:2166 +0x38
github.com/Notifiarr/notifiarr/pkg/client.(*Client).fixForwardedFor-fm.(*Client).fixForwardedFor.func1({0x103ac3900, 0x14000462ae0}, 0x140010d26c0)
	/Volumes/Storage/david/go/src/github.com/Notifiarr/notifiarr/pkg/client/handlers.go:233 +0x250
net/http.HandlerFunc.ServeHTTP(0x140010d25a0?, {0x103ac3900?, 0x14000462ae0?}, 0x102fc1a44?)
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:2166 +0x38
github.com/gorilla/mux.(*Router).ServeHTTP(0x14000728180, {0x103ac3900, 0x14000462ae0}, 0x140010d2480)
	/Users/david/go/pkg/mod/github.com/gorilla/mux@v1.8.1/mux.go:212 +0x194
github.com/Notifiarr/notifiarr/pkg/client.(*Client).StartWebServer.(*ApacheLog).Wrap.func1({0x103ac3b40, 0x14001060000}, 0x140010d2480)
	/Users/david/go/pkg/mod/github.com/lestrrat-go/apache-logformat/v2@v2.0.6/logformat.go:65 +0x134
net/http.HandlerFunc.ServeHTTP(0x1400108d200?, {0x103ac3b40?, 0x14001060000?}, 0x1400108a2e4?)
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:2166 +0x38
github.com/Notifiarr/notifiarr/pkg/client.(*Client).StartWebServer.(*Client).stripSecrets.func2({0x103ac3b40, 0x14001060000}, 0x140010d2480)
	/Volumes/Storage/david/go/src/github.com/Notifiarr/notifiarr/pkg/client/handlers.go:184 +0xe4
net/http.HandlerFunc.ServeHTTP(0x1400069a1a0?, {0x103ac3b40?, 0x14001060000?}, 0x102fb9708?)
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:2166 +0x38
net/http.(*ServeMux).ServeHTTP(0x0?, {0x103ac3b40, 0x14001060000}, 0x140010d2480)
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:2683 +0x1a4
net/http.serverHandler.ServeHTTP({0x14000804600?}, {0x103ac3b40?, 0x14001060000?}, 0x6?)
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:3137 +0xbc
net/http.(*conn).serve(0x14000162cf0, {0x103ac5888, 0x14000784180})
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:2039 +0x508
created by net/http.(*Server).Serve in goroutine 16
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/net/http/server.go:3285 +0x3f0
```
^ this happens trying to encode a `map[int]string` with 9 items.
The change: https://cs.opensource.google/go/go/+/4c5dac72029bb3dd4559a2fafe566bed71f22c42

File: pkg/client/html_templates.go [hunk 1]
```diff
@@ -447,6 +450,8 @@ func (c *Client) renderTemplate(
 		ClientInfo:  clientInfo,
 		Disks:       c.getDisks(ctx),
 		Headers:     req.Header,
+		Tunnel:      c.tunnel.Config,
+		PoolStats:   c.tunnel.PoolStats(),
```
Comment (davidnewhall) [inline pkg/client/html_templates.go:454]: Instead of pass in pieces of `c.tunnel`, pass in the whole thing so we can `if` statement it in the template. Sometimes `c.tunnel` is `nil`, and line 454 causes a crash.

File: pkg/bindata/templates/tunnel.html [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+    for opening a port, or having a static IP. This page allows you to select your
+    primary tunnel and which tunnel you wish to use as backup in case the primary
+    becomes inaccessible.
+</p>
+<p>
+    Click the <span class="text-brand">Ping</span> button, and select the tunnel with the fastest response time as your primary.
+    Select any other tunnel as backup. Again, choose one with a faster response time.
+</p>
+<p>
+    <li><i class="fas fa-star text-dgrey"></i> Active Tunnel: <b>{{(cache "activeTunnel").Data}}</b></li>
```
Comment (davidnewhall) [inline pkg/bindata/templates/tunnel.html:15]: Sometimes this is nil, check it before accessing `.Data`
